local temper = require('temper-core');
local pointEquals, isOpposite, directionDelta, nextRandom, newGame, changeDirection, tick, Point, Playing, Right, Down, Up, Left, GameOver, SnakeGame, exports;
pointEquals = temper.import('snake', 'pointEquals');
isOpposite = temper.import('snake', 'isOpposite');
directionDelta = temper.import('snake', 'directionDelta');
nextRandom = temper.import('snake', 'nextRandom');
newGame = temper.import('snake', 'newGame');
changeDirection = temper.import('snake', 'changeDirection');
tick = temper.import('snake', 'tick');
Point = temper.import('snake', 'Point');
Playing = temper.import('snake', 'Playing');
Right = temper.import('snake', 'Right');
Down = temper.import('snake', 'Down');
Up = temper.import('snake', 'Up');
Left = temper.import('snake', 'Left');
GameOver = temper.import('snake', 'GameOver');
SnakeGame = temper.import('snake', 'SnakeGame');
exports = {};
return exports;
