local temper = require('temper-core');
local pointEquals, isOpposite, directionDelta, nextRandom, newGame, changeDirection, tick, newMultiGame, multiTick, multiRender, changePlayerDirection, isMultiGameOver, addPlayer, removePlayer, directionToString, stringToDirection, Point, Playing, Right, Down, Up, Left, GameOver, SnakeGame, PlayerSnake, Dead, Alive, exports;
pointEquals = temper.import('snake', 'pointEquals');
isOpposite = temper.import('snake', 'isOpposite');
directionDelta = temper.import('snake', 'directionDelta');
nextRandom = temper.import('snake', 'nextRandom');
newGame = temper.import('snake', 'newGame');
changeDirection = temper.import('snake', 'changeDirection');
tick = temper.import('snake', 'tick');
newMultiGame = temper.import('snake', 'newMultiGame');
multiTick = temper.import('snake', 'multiTick');
multiRender = temper.import('snake', 'multiRender');
changePlayerDirection = temper.import('snake', 'changePlayerDirection');
isMultiGameOver = temper.import('snake', 'isMultiGameOver');
addPlayer = temper.import('snake', 'addPlayer');
removePlayer = temper.import('snake', 'removePlayer');
directionToString = temper.import('snake', 'directionToString');
stringToDirection = temper.import('snake', 'stringToDirection');
Point = temper.import('snake', 'Point');
Playing = temper.import('snake', 'Playing');
Right = temper.import('snake', 'Right');
Down = temper.import('snake', 'Down');
Up = temper.import('snake', 'Up');
Left = temper.import('snake', 'Left');
GameOver = temper.import('snake', 'GameOver');
SnakeGame = temper.import('snake', 'SnakeGame');
PlayerSnake = temper.import('snake', 'PlayerSnake');
Dead = temper.import('snake', 'Dead');
Alive = temper.import('snake', 'Alive');
temper.run_scheduler();
exports = {};
return exports;
